### ISSUE TITLE
Different types of payload for pubnub push notification

### ISSUE THREAD

**Issue by thakurakhilesh** [sourcefuse/loopback4-notifications#29]
Can use configurable firebase notification payload object instead of data payload only

Please check the different type of payloads
https://firebase.google.com/docs/cloud-messaging/concept-options 

Additional Context - 

the [fcm-provider](https://github.com/sourcefuse/loopback4-notifications/blob/master/src/providers/push/fcm/fcm.provider.ts) has a similar functionality already Implemented, the fcm-provided can refactor and reuse that same code to provide this in the pubnub notification provided.

**Comment by akshatdubeysf** [comment]
@jyoti-13
