### ISSUE TITLE
Says aws-sdk missing even when I just need to use the Pubnub Notifications.

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-notifications#30]
**Describe the bug**
After installing the package and running the project, it says 'aws-sdk' is missing.

**To Reproduce**
1. Install the 'loopback4-notifications' package.
2. Follow the readme usage steps for Pubnub notifications.
3. Run the application.
4. It throws an error saying 'aws-sdk' is required.

**Expected behavior**
It should not ask to install 'aws-sdk' when I don't need it.

**Comment by akshatdubeysf** [comment]
@Jyoti-13

**Comment by saigonbitmaster** [comment]
https://github.com/saigonbitmaster/justToShare
