### ISSUE TITLE
PushNotification is not exported using any main or /push 

### ISSUE THREAD

**Issue by vaibhavkumar-sf** [sourcefuse/loopback4-notifications#82]
**Describe the bug**
to use PushNotification, we need to import it like : 

`import {PushNotification} from 'loopback4-notifications/dist/providers/push/index';`

**Expected behavior**
It must be like : 
`import {PushNotification} from 'loopback4-notifications/push'`

**Comment by yeshamavani** [comment]
Solved.. Closing it
